name: Full Test and Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-and-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Run Jest Tests
        run: npm test

  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-and-integration-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci

      # ✅ Install required system dependencies for Electron
      - name: Install Electron dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-0 \
            libnss3 \
            libxss1 \
            libasound2 \
            libgbm1 \
            libx11-xcb1 \
            xvfb

      # ✅ Install Playwright browsers and dependencies
      - name: Install Electron dependencies
        run: |
          sudo apt-get update
          # Try installing new t64 audio library (Ubuntu 24.04)
          if sudo apt-get install -y libasound2t64; then
            echo "✅ Installed libasound2t64"
          else
            echo "⚠️ Falling back to libasound2"
            sudo apt-get install -y libasound2 || true
          fi
          sudo apt-get install -y \
            libgtk-3-0 \
            libnss3 \
            libxss1 \
            libgbm1 \
            libx11-xcb1 \
            xvfb


      # ✅ Run Playwright tests using virtual framebuffer
      - name: Run E2E Tests
        run: xvfb-run -a npm run test:e2e

  build:
    needs: [unit-and-integration-tests, e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Build application
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: todo-app-linux
          path: dist/
